### ISSUE TITLE
effort of time 

### ISSUE THREAD

**Issue by haytxy** [Icinga/L10n#57]
Could someone please specify how much time it takes to create a new location from scratch?
just example. I will be very appreciated.

**Comment by nilmerg** [comment]
Well, there are currently 4587 messages in the catalog. Assuming you can translate each message within 3 minutes (average) you'd sit there translating for 230 hours or ~10 days straight.

I'd suggest to take breaks, though. :rofl: Or ask others for help. It's also not a requirement to only provide a 100% translation. Any amount of progress is welcome.
