### ISSUE TITLE
A little issue in the german translation

### ISSUE THREAD

**Issue by K0nne** [Icinga/L10n#58]
## Describe the bug
Hi!

I stumbled across a litttle issue in the german translation.

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

0. use the german translation
1. have a check with >2 graphs
2. click on "Mehr anzeigen" to expand
3. click on "show less" to shrink it

## Expected behavior

"show less" should be "Weniger anzeigen"

## Screenshots

![21-04-_2021_10-07-46](https://user-images.githubusercontent.com/34264690/115520006-018aeb00-a28a-11eb-956c-3e39c932ec27.png)

![21-04-_2021_10-07-59](https://user-images.githubusercontent.com/34264690/115520028-05b70880-a28a-11eb-8fe3-644d75b457cb.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version
    2.7.4
Git Commit
    3ebfb5c38330d22966d24d2ace57d7eb3fb2a6db
PHP Version
    7.1.8
Git Commit Datum
    2020-08-17
Copyright
    © 2013-2021 Das Icinga Projekt 
```
* Web browser used:

`Firefox`

* Icinga 2 version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: v2.11.8-4-g57e8fd392)

Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Red Hat Enterprise Linux Server
  Platform version: 7.9 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-1160.24.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-322-concurrent-0
```

**Comment by nilmerg** [comment]
Moved to https://github.com/Icinga/L10n

**Comment by nilmerg** [comment]
Ehm, I can't find this term in our catalog nor in any of our code bases. Which module is showing the graphs there? (I suppose the term originates from the module)

**Comment by K0nne** [comment]
Oh, we are using graphite 1.1.0 for visualization.

**Comment by nilmerg** [comment]
Okay, though I can't find `Show Less` in either [the graphite module](https://github.com/Icinga/icingaweb2-module-graphite/search?q=%22Show+Less%22) nor in the entire [Icinga org](https://github.com/search?q=org%3AIcinga+%22Show+Less%22&type=code) :man_shrugging:

**Comment by K0nne** [comment]
Strange ^^ Maybe this can help you to locate it:

![21-04-_2021_11-53-03](https://user-images.githubusercontent.com/34264690/115534786-6b11f600-a298-11eb-9159-ded7498be16b.png)

**Comment by nilmerg** [comment]
Ahhh, the Github search doesn't take pre-selected tags into account. That's code that [has been removed](https://github.com/Icinga/icingaweb2-module-graphite/issues/202) since v1.1.0, hence why I couldn't find anything.

I'll close here then.

**Comment by K0nne** [comment]
Ahh, thanks for your efforts! 
Lets hope 1.2.0 is getting a release some day.
