### ISSUE TITLE
Duplicate rows (ru_RU)

### ISSUE THREAD

**Issue by krote5k** [Icinga/L10n#8]
Duplicate rows:
* Failed to succesfully validate the configuration: %s
* Password
* Port
* Skip Validation
* SSL CA
* SSL CA Path
* SSL Certificate
* SSL Do Not Verify Server Certificate
* SSL Key
* The CA certificate file path
* The Configuration has been successfully validated.
* Validate Configuration
* Validation in Progress
* Validation Log

**Comment by nilmerg** [comment]
Hi,

these duplicates are only in your version of the file.

You can eliminate them by using the `msguniq` program. (may be included in Poedit, otherwise install the `gettext` package)

`msguniq -u --use-first --sort-by-file src/ru_RU/LC_MESSAGES/icinga.po > src/ru_RU/LC_MESSAGES/icinga.po`

**Comment by nilmerg** [comment]
I guess this can be closed :)
